// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matheus-aicorp/sample-test-project/internal/domain (interfaces: CapitalRepository,WeatherProvider,Clock)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_domain.go -package=mocks github.com/matheus-aicorp/sample-test-project/internal/domain CapitalRepository,WeatherProvider,Clock
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/matheus-aicorp/sample-test-project/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCapitalRepository is a mock of CapitalRepository interface.
type MockCapitalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCapitalRepositoryMockRecorder
	isgomock struct{}
}

// MockCapitalRepositoryMockRecorder is the mock recorder for MockCapitalRepository.
type MockCapitalRepositoryMockRecorder struct {
	mock *MockCapitalRepository
}

// NewMockCapitalRepository creates a new mock instance.
func NewMockCapitalRepository(ctrl *gomock.Controller) *MockCapitalRepository {
	mock := &MockCapitalRepository{ctrl: ctrl}
	mock.recorder = &MockCapitalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapitalRepository) EXPECT() *MockCapitalRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockCapitalRepository) All() []domain.Capital {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].([]domain.Capital)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockCapitalRepositoryMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockCapitalRepository)(nil).All))
}

// BySlug mocks base method.
func (m *MockCapitalRepository) BySlug(slug string) (domain.Capital, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BySlug", slug)
	ret0, _ := ret[0].(domain.Capital)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// BySlug indicates an expected call of BySlug.
func (mr *MockCapitalRepositoryMockRecorder) BySlug(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BySlug", reflect.TypeOf((*MockCapitalRepository)(nil).BySlug), slug)
}

// MockWeatherProvider is a mock of WeatherProvider interface.
type MockWeatherProvider struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherProviderMockRecorder
	isgomock struct{}
}

// MockWeatherProviderMockRecorder is the mock recorder for MockWeatherProvider.
type MockWeatherProviderMockRecorder struct {
	mock *MockWeatherProvider
}

// NewMockWeatherProvider creates a new mock instance.
func NewMockWeatherProvider(ctrl *gomock.Controller) *MockWeatherProvider {
	mock := &MockWeatherProvider{ctrl: ctrl}
	mock.recorder = &MockWeatherProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherProvider) EXPECT() *MockWeatherProviderMockRecorder {
	return m.recorder
}

// CurrentWeather mocks base method.
func (m *MockWeatherProvider) CurrentWeather(ctx context.Context, capitals []domain.Capital) ([]domain.CurrentWeather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentWeather", ctx, capitals)
	ret0, _ := ret[0].([]domain.CurrentWeather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentWeather indicates an expected call of CurrentWeather.
func (mr *MockWeatherProviderMockRecorder) CurrentWeather(ctx, capitals any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentWeather", reflect.TypeOf((*MockWeatherProvider)(nil).CurrentWeather), ctx, capitals)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
