// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/matheus-aicorp/sample-test-project/internal/adapter/driving/rest (interfaces: WeatherQuery)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/mock_rest.go -package=mocks github.com/matheus-aicorp/sample-test-project/internal/adapter/driving/rest WeatherQuery
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/matheus-aicorp/sample-test-project/internal/application"
	gomock "go.uber.org/mock/gomock"
)

// MockWeatherQuery is a mock of WeatherQuery interface.
type MockWeatherQuery struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherQueryMockRecorder
	isgomock struct{}
}

// MockWeatherQueryMockRecorder is the mock recorder for MockWeatherQuery.
type MockWeatherQueryMockRecorder struct {
	mock *MockWeatherQuery
}

// NewMockWeatherQuery creates a new mock instance.
func NewMockWeatherQuery(ctrl *gomock.Controller) *MockWeatherQuery {
	mock := &MockWeatherQuery{ctrl: ctrl}
	mock.recorder = &MockWeatherQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherQuery) EXPECT() *MockWeatherQueryMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockWeatherQuery) Execute(ctx context.Context, slugs []string) (*application.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, slugs)
	ret0, _ := ret[0].(*application.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockWeatherQueryMockRecorder) Execute(ctx, slugs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockWeatherQuery)(nil).Execute), ctx, slugs)
}
